# Generated by Django 5.0.4 on 2024-05-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receviemessage',
            name='date_time_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
