# Generated by Django 5.0.4 on 2024-05-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_receviemessage_date_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='receviemessage',
            name='first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receviemessage',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
