# Generated by Django 5.0.4 on 2024-05-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_receviemessage_first_name_receviemessage_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receviemessage',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='receviemessage',
            name='last_name',
        ),
        migrations.AddField(
            model_name='receviemessage',
            name='full_name',
            field=models.CharField(default=1, max_length=150, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
