# Generated by Django 5.0.4 on 2024-05-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='descrisption',
            new_name='description',
        ),
    ]
