# Generated by Django 5.0.4 on 2024-05-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_skills_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receviemessage',
            options={'verbose_name': 'receviemessage', 'verbose_name_plural': 'receviemessage'},
        ),
    ]
