# Generated by Django 5.0.4 on 2024-05-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'information', 'verbose_name_plural': 'information'},
        ),
    ]
