# Generated by Django 5.0.4 on 2024-05-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_information_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='address',
            field=models.CharField(max_length=150, verbose_name='address'),
        ),
    ]
