# Generated by Django 5.0.4 on 2024-05-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_information_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.AlterModelOptions(
            name='receviemessage',
            options={'verbose_name': 'RecevieMessage', 'verbose_name_plural': 'RecevieMessage'},
        ),
        migrations.AlterField(
            model_name='receviemessage',
            name='date_time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date time created'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='course',
            field=models.CharField(max_length=150, verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='date_time_create',
            field=models.DateTimeField(auto_now=True, verbose_name='date time created'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name of course'),
        ),
    ]
