# Generated by Django 5.0.4 on 2024-05-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_delete_information_alter_receviemessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='date_time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date time created'),
        ),
    ]
