# Generated by Django 5.0.4 on 2024-05-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_otherskills_alter_skills_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherSkills',
        ),
    ]
