# Generated by Django 5.0.4 on 2024-05-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_delete_otherskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('image', models.ImageField(upload_to='cover/', verbose_name='image')),
                ('date_time_created', models.DateTimeField(auto_now_add=True, verbose_name='date time create')),
            ],
        ),
    ]
