# Generated by Django 5.0.4 on 2024-05-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolio'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
